import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const __dirname = import.meta.dirname;
const rulesPath = resolve(__dirname, '..', 'rules', 'AGENTS.md');

const content = readFileSync(rulesPath, 'utf-8');
const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');

const output = `// This file is auto-generated by scripts/build-rules.ts
// Do not edit manually — edit rules/AGENTS.md instead.

export const RULES_CONTENT: string = \`${escaped}\`;
`;

const outPath = resolve(__dirname, '..', 'src', 'rules-content.ts');
writeFileSync(outPath, output, 'utf-8');
