packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@types/node': ^24
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  '@changesets/cli': ^2.31.0
  '@changesets/changelog-github': ^0.7.0
  '@fontsource-variable/noto-serif': ^5.2.9
  '@fontsource-variable/sn-pro': ^5.2.1
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  esbuild: true
  msgpackr-extract: false
  sharp: true
