packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@types/node': ^24
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  '@changesets/cli': ^2.31.0
  '@changesets/changelog-github': ^0.7.0
  '@fontsource-variable/noto-serif': ^5.2.9
  '@fontsource-variable/sn-pro': ^5.2.1
  '@earendil-works/pi-coding-agent': '*'
  '@earendil-works/pi-ai': '*'
  '@gotgenes/pi-subagents': '^17.0.0'
  'typebox': '*'
  '@astrojs/starlight': ^0.41.0
  astro: 7.0.2
  all-contributors-cli: ^6.26.1
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  '@google/genai': true
  esbuild: true
  msgpackr-extract: false
  onnxruntime-node: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri@0.3.2'
  - '@astrojs/starlight@0.41.0'
  - astro@7.0.2
  - effect@4.0.0-beta.92
