// packages/opencode/sync.config.ts
// Sync config: derives opencode agent files from canonical core directives
//
// oxlint-disable sort-keys -- Permission maps keep their declared glob order because the sync
// engine projects object keys verbatim into generated agent frontmatter, and `check-sync`
// enforces byte identity of that committed output. Sorting keys here would churn every
// generated permission block without changing behavior.

import type { SyncConfig } from '../core/scripts/lib/config.js';

export default {
  files: {
    'adventurer.md': {
      frontmatter: {
        description: `Codebase reconnaissance agent for mapping unfamiliar code, tracing call chains, and reporting verified context without implementing changes.`,
        mode: 'subagent',
        permission: {
          bash: {
            '*': 'ask',
            'ls*': 'allow',
            'cat*': 'allow',
            'echo*': 'allow',
            'head*': 'allow',
            'tail*': 'allow',
            'grep*': 'allow',
            'rg*': 'allow',
            'wc*': 'allow',
            'which*': 'allow',
            'diff*': 'allow',
            'stat*': 'allow',
            'pwd*': 'allow',
            'cd*': 'allow',
            'find*': 'allow',
            'printf*': 'allow',
            'git log*': 'allow',
            'git diff*': 'allow',
            'git status*': 'allow',
            'git show*': 'allow',
            'git branch*': 'allow',
            'git rev-parse*': 'allow',
            'git remote*': 'allow',
            'git stash*': 'allow',
            'git config*': 'allow',
            'pnpm*': 'allow',
            'npm*': 'allow',
            'opensrc*': 'allow',
            'agent-browser*': 'allow',
            'rtk*': 'allow',
          },
          edit: 'deny',
          glob: 'allow',
          grep: 'allow',
          lsp: 'allow',
          read: 'allow',
          skill: 'allow',
          todowrite: 'allow',
          webfetch: 'allow',
          websearch: 'ask',
        },
      },
    },
    'architect.md': {
      frontmatter: {
        description: `Architecture decision agent for comparing implementation approaches, boundaries, threat models, and ADR decisions.`,
        mode: 'subagent',
        permission: {
          bash: {
            '*': 'ask',
            'ls*': 'allow',
            'cat*': 'allow',
            'echo*': 'allow',
            'head*': 'allow',
            'tail*': 'allow',
            'grep*': 'allow',
            'rg*': 'allow',
            'wc*': 'allow',
            'which*': 'allow',
            'diff*': 'allow',
            'stat*': 'allow',
            'pwd*': 'allow',
            'cd*': 'allow',
            'find*': 'allow',
            'printf*': 'allow',
            'git diff*': 'allow',
            'git log*': 'allow',
            'git status*': 'allow',
            'git show*': 'allow',
            'git branch*': 'allow',
            'opensrc*': 'allow',
            'pnpm*': 'allow',
            'npm*': 'allow',
            'npm view *': 'allow',
          },
          edit: 'deny',
          glob: 'allow',
          grep: 'allow',
          lsp: 'allow',
          read: 'allow',
          skill: 'allow',
          webfetch: 'allow',
          websearch: 'ask',
        },
      },
    },
    'builder.md': {
      frontmatter: {
        description: `Focused implementation agent for one atomic, verifiable feature, fix, test, or refactor.`,
        mode: 'subagent',
        permission: {
          bash: {
            // Read-only file operations (Claude Code baseline)
            'ls*': 'allow',
            'cat*': 'allow',
            'echo*': 'allow',
            'head*': 'allow',
            'tail*': 'allow',
            'grep*': 'allow',
            'rg*': 'allow',
            'wc*': 'allow',
            'which*': 'allow',
            'diff*': 'allow',
            'stat*': 'allow',
            'du*': 'allow',
            'pwd*': 'allow',
            'cd*': 'allow',
            'find*': 'allow',
            'printf*': 'allow',
            'test*': 'allow',
            'sort*': 'allow',
            'git*': 'allow',
            'pnpm*': 'allow',
            'npm*': 'allow',
            'pnpx*': 'ask',
            'tsc*': 'allow',
            'vitest*': 'allow',
            'vp*': 'allow',
            'rtk*': 'allow',
            'eslint*': 'allow',
            'prettier*': 'allow',
            '*': 'ask',
          },
          edit: 'allow',
          glob: 'allow',
          grep: 'allow',
          lsp: 'allow',
          read: 'allow',
          skill: 'allow',
          todowrite: 'allow',
          webfetch: 'allow',
        },
      },
    },
    'commands/blitz.md': {
      output: 'commands/blitz.md',
      stripFrontmatter: true,
    },
    'commands/fein.md': {
      output: 'commands/fein.md',
      stripFrontmatter: true,
    },
    'commands/sonar.md': {
      output: 'commands/sonar.md',
      stripFrontmatter: true,
    },
    'diagnose.md': {
      frontmatter: {
        description: `Systematic regression-tracing agent from symptom and error evidence to root cause, fix, and prevention.`,
        mode: 'subagent',
        permission: {
          bash: {
            // Read-only file operations
            'ls*': 'allow',
            'cat*': 'allow',
            'echo*': 'allow',
            'head*': 'allow',
            'tail*': 'allow',
            'grep*': 'allow',
            'rg*': 'allow',
            'wc*': 'allow',
            'which*': 'allow',
            'diff*': 'allow',
            'stat*': 'allow',
            'pwd*': 'allow',
            'cd*': 'allow',
            'find*': 'allow',
            'printf*': 'allow',
            'git status*': 'allow',
            'git diff*': 'allow',
            'git log*': 'allow',
            'git blame*': 'allow',
            'git show*': 'allow',
            env: 'allow',
            pwd: 'allow',
            // Catch-all - unusual/dangerous commands still ask
            '*': 'ask',
          },
          edit: 'allow',
          glob: 'allow',
          grep: 'allow',
          lsp: 'allow',
          read: 'allow',
          skill: 'allow',
          todowrite: 'allow',
          webfetch: 'allow',
          websearch: 'ask',
        },
      },
    },
    'orchestrator.md': {
      frontmatter: {
        description: `Maestria workflow dispatcher for routing work, preserving handoffs, and keeping independent review explicit.`,
        mode: 'all',
        permission: {
          bash: {
            '*': 'deny',
            '* npx --yes skills@latest *': 'allow',
          },
          edit: 'deny',
          glob: 'deny',
          grep: 'deny',
          lsp: 'deny',
          question: 'allow',
          read: 'deny',
          skill: 'allow',
          task: {
            '*': 'deny',
            adventurer: 'allow',
            architect: 'allow',
            builder: 'allow',
            diagnose: 'allow',
            planner: 'allow',
            reviewer: 'allow',
            writer: 'allow',
          },
          todowrite: 'allow',
          webfetch: 'deny',
        },
      },
    },
    'planner.md': {
      frontmatter: {
        description: `Phased planning agent with dependencies, verification criteria, timelines, and rollback points.`,
        mode: 'subagent',
        permission: {
          bash: {
            '*': 'ask',
            // Read-only file operations
            'ls*': 'allow',
            'cat*': 'allow',
            'echo*': 'allow',
            'head*': 'allow',
            'tail*': 'allow',
            'grep*': 'allow',
            'rg*': 'allow',
            'wc*': 'allow',
            'which*': 'allow',
            'diff*': 'allow',
            'stat*': 'allow',
            'pwd*': 'allow',
            'cd*': 'allow',
            'find*': 'allow',
            'printf*': 'allow',
            // Git operations
            'git status*': 'allow',
            'git diff*': 'allow',
            'git log*': 'allow',
            'git show*': 'allow',
            'git branch*': 'allow',
            'git rev-parse*': 'allow',
            'mkdir*': 'allow',
            // Package managers
            'pnpm*': 'allow',
            'npm*': 'allow',
          },
          edit: 'ask',
          glob: 'allow',
          grep: 'allow',
          lsp: 'allow',
          read: 'allow',
          skill: 'allow',
          todowrite: 'allow',
          webfetch: 'allow',
        },
      },
    },
    'reviewer.md': {
      frontmatter: {
        description: `Independent review agent covering correctness, security, performance, maintainability, and quality gates.`,
        mode: 'subagent',
        permission: {
          bash: {
            '*': 'ask',
            // Read-only file operations
            'ls*': 'allow',
            'cat*': 'allow',
            'echo*': 'allow',
            'head*': 'allow',
            'tail*': 'allow',
            'grep*': 'allow',
            'rg*': 'allow',
            'wc*': 'allow',
            'which*': 'allow',
            'diff*': 'allow',
            'stat*': 'allow',
            'pwd*': 'allow',
            'cd*': 'allow',
            'find*': 'allow',
            'printf*': 'allow',
            // Git operations
            'git status*': 'allow',
            'git diff*': 'allow',
            'git log*': 'allow',
            'git show*': 'allow',
            'git branch*': 'allow',
            'git rev-parse*': 'allow',
            // Package managers
            'pnpm*': 'allow',
            'npm*': 'allow',
            // Build, test, lint tools
            'vp*': 'allow',
            'rtk*': 'allow',
            'node*': 'allow',
          },
          edit: 'deny',
          glob: 'allow',
          grep: 'allow',
          lsp: 'allow',
          read: 'allow',
          skill: 'allow',
          webfetch: 'allow',
        },
      },
    },
    'rules.md': {
      output: '../rules/AGENTS.md',
    },
    'writer.md': {
      frontmatter: {
        description: `Structured documentation agent for READMEs, API docs, architecture documents, changelogs, and decision records.`,
        mode: 'subagent',
        permission: {
          bash: {
            '*': 'ask',
            // Read-only file operations
            'ls*': 'allow',
            'cat*': 'allow',
            'echo*': 'allow',
            'head*': 'allow',
            'tail*': 'allow',
            'grep*': 'allow',
            'rg*': 'allow',
            'wc*': 'allow',
            'which*': 'allow',
            'diff*': 'allow',
            'stat*': 'allow',
            'pwd*': 'allow',
            'cd*': 'allow',
            'find*': 'allow',
            'printf*': 'allow',
            // Git operations
            'git status*': 'allow',
            'git diff*': 'allow',
            'git log*': 'allow',
            'git show*': 'allow',
            'git branch*': 'allow',
            'git rev-parse*': 'allow',
            // Package managers
            'pnpm*': 'allow',
            'npm*': 'allow',
            'npm view *': 'allow',
            // Build, test, lint tools
            'vp*': 'allow',
            'mkdir*': 'allow',
          },
          edit: 'allow',
          glob: 'allow',
          grep: 'allow',
          lsp: 'allow',
          read: 'allow',
          skill: 'allow',
          todowrite: 'allow',
          webfetch: 'allow',
        },
      },
    },
  },
  output: 'agents',
  source: '../core/agent-directives/specialists',
} satisfies SyncConfig;
