#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { parse, stringify } from 'yaml';

const ROLES = ['adventurer', 'architect', 'builder', 'diagnose', 'planner', 'reviewer', 'writer'];
const MODES = ['blitz', 'fein', 'sonar'];
const SHARED_SKILLS = [
  ...ROLES,
  ...MODES,
  'orchestrator',
  'global-rules',
  'handoff',
  'iteration-limits',
];
const NOTICE =
  '<!-- Generated by scripts/sync-consolidated-plugin.ts. Edit its inputs and regenerate. -->';
const HOST_LIMIT =
  'Live host loading is unverified. Package and sync checks validate the shipped files, not runtime discovery or enforcement.';
const NATIVE_CONTEXTS = [
  ['claude-code', 'integrations/claude-code/orchestrator.md', '## Claude Code Integration'],
  ['cursor', 'integrations/cursor/orchestrator.md', '## Specialist Agents (Cursor)'],
  ['codex', 'integrations/codex/context.md', '## Codex CLI Integration'],
  [
    'kimi-code',
    'integrations/kimi-code/skills/orchestrator/SKILL.md',
    '## Specialist → Subagent Routing',
  ],
] as const;

const assertContainedFile = (packageRoot: string, relative: string): string => {
  const absolute = path.resolve(packageRoot, relative);
  if (!absolute.startsWith(`${packageRoot}${path.sep}`)) {
    throw new Error(`Resource escapes plugin root: ${relative}`);
  }
  let current = path.parse(absolute).root;
  for (const part of absolute.slice(current.length).split(path.sep)) {
    current = path.join(current, part);
    let linked = false;
    try {
      linked = fs.lstatSync(current).isSymbolicLink();
    } catch (error) {
      if (!(error instanceof Error && 'code' in error && error.code === 'ENOENT')) {
        throw error;
      }
    }
    if (linked) {
      throw new Error(`Plugin resource must not be a symlink: ${relative}`);
    }
  }
  return absolute;
};

const readInput = (packageRoot: string, relative: string): string => {
  const absolute = assertContainedFile(packageRoot, relative);
  if (!fs.existsSync(absolute) || !fs.statSync(absolute).isFile()) {
    throw new Error(`Required plugin input is missing or not a file: ${relative}`);
  }
  return fs.readFileSync(absolute, 'utf-8');
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

const nativeInputs = (): string[] => [
  ...ROLES.flatMap((role) => [
    `agents/claude-code/${role}.md`,
    `agents/cursor/${role}.md`,
    `agents/codex/maestria-${role}.toml`,
    `integrations/kimi-code/skills/${role}/SKILL.md`,
  ]),
  ...MODES.flatMap((mode) => [
    `commands/claude-code/${mode}.md`,
    `commands/cursor/${mode}.md`,
    `commands/kimi-code/${mode}.md`,
  ]),
  'rules/cursor/maestria-global.mdc',
  'integrations/claude-code/global-rules.md',
  'integrations/codex/instructions/AGENTS.md',
  'integrations/kimi-code/SYSTEM.md',
];

const roleAgent = (text: string, role: string): string => {
  const match = /^---\n(?<frontmatter>[\s\S]*?)\n---\n(?<body>[\s\S]*)$/u.exec(text);
  if (!match?.groups) {
    throw new Error(`Missing skill frontmatter: ${role}`);
  }
  const metadata: unknown = parse(match.groups.frontmatter);
  if (!isRecord(metadata)) {
    throw new Error(`Invalid skill frontmatter: ${role}`);
  }
  const { name, description } = metadata;
  if (name !== role || typeof description !== 'string' || description.trim() === '') {
    throw new Error(`Invalid name or description in skill frontmatter: ${role}`);
  }
  return `---\n${stringify({ description, name }, { lineWidth: 0 })}---\n\n${NOTICE}\n\n${match.groups.body.trim()}\n`;
};

const nativeGuide = (host: string, context: string): string => {
  const prefixes: Record<string, string> = { 'claude-code': 'maestria:', codex: 'maestria-' };
  const prefix = prefixes[host] ?? '';
  const roles = ROLES.map((role) => `| ${role} | \`${prefix}${role}\` |`).join('\n');
  const mapping =
    host === 'kimi-code' ? '' : `\n| Portable role | Native agent |\n| --- | --- |\n${roles}\n`;
  return `${NOTICE}\n\n# ${host} Integration\n\nRead this guide only when ${host} is the active host. The shared portable skills define methodology; the host owns tools, delegation, permissions, and lifecycle.${mapping}\n${context.trim()}\n\n${HOST_LIMIT}\n`;
};

const advisoryGuide = (host: 'devin' | 'zcode'): string => {
  const hostText =
    host === 'devin'
      ? 'Devin loads the shared skills from `skills/` and the conventional root `agents/<role>.md` profiles as `maestria:<role>`. Custom plugin subagents are available in local CLI and Desktop sessions, not cloud sessions. Use the host-provided subagent controls with a complete handoff; this package does not prescribe a fabricated tool API. Workflow modes are skills: `/maestria:fein`, `/maestria:sonar`, and `/maestria:blitz`.\n\nSee the [Devin plugin documentation](https://docs.devin.ai/cli/extensibility/plugins/overview).'
      : 'ZCode selects the shared `skills/` corpus and the explicit root `agents/<role>.md` files through `.zcode-plugin/plugin.json`. Use the installed plugin subagents through the controls the host exposes. The manifest disables command discovery; invoke the fein, sonar, and blitz skills through the Skills group. It does not load the Claude or Cursor command prompts or assume their delegation API.\n\nSee the [ZCode plugin documentation](https://zcode.z.ai/en/docs/plugin).';
  return `${NOTICE}\n\n# ${host} Integration\n\n${hostText}\n\nLoad global-rules once per session. Keep exploration, planning, and review read-only and retain independent maker/checker roles. The root agent profiles contain name and description frontmatter plus portable role guidance. Their restrictions are advisory; no runtime tool-denial or sandbox setting is claimed for these hosts.\n\n${HOST_LIMIT}\n`;
};

const hermesGuide = (): string => `${NOTICE}

# Hermes Integration

Hermes consumes the root Agent Plugins v1 manifest and shared skills. Enable the staged package explicitly through the host's plugin flow, then use \`skills_list\` to discover each full qualified name and \`skill_view\` to load it. Hermes generates an \`agent-plugin-<slug>-<hash>\` namespace; do not assume \`maestria:<skill>\`.

Load global-rules and orchestrator by their discovered names. Apply portable role guidance within the tools and delegation controls the host exposes. Portable skills do not supply a trust policy, permissions, or sandbox. This bundle includes no Python adapter, native Hermes hooks, or MCP declaration.

See [Hermes portable package support](https://hermes-agent.nousresearch.com/docs/developer-guide/plugins#portable-agent-plugins-v1-packages).

${HOST_LIMIT}
`;

const outputPlan = (packageRoot: string): Map<string, string> => {
  const plan = new Map<string, string>();
  for (const skill of SHARED_SKILLS) {
    const text = readInput(packageRoot, `skills/${skill}/SKILL.md`);
    if (ROLES.includes(skill)) {
      plan.set(`agents/${skill}.md`, roleAgent(text, skill));
    }
  }
  for (const relative of nativeInputs()) {
    readInput(packageRoot, relative);
  }
  for (const [host, source, heading] of NATIVE_CONTEXTS) {
    const text = readInput(packageRoot, source);
    const start = text.indexOf(heading);
    if (start === -1) {
      throw new Error(`Missing native integration heading ${heading}: ${source}`);
    }
    plan.set(`integrations/${host}/README.md`, nativeGuide(host, text.slice(start)));
  }
  for (const host of ['devin', 'zcode'] as const) {
    plan.set(`integrations/${host}/README.md`, advisoryGuide(host));
  }
  plan.set('integrations/hermes/README.md', hermesGuide());
  return plan;
};

const staleAgents = (packageRoot: string, plan: Map<string, string>): string[] => {
  const agentsRoot = assertContainedFile(packageRoot, 'agents');
  if (!fs.existsSync(agentsRoot)) {
    return [];
  }
  return fs
    .readdirSync(agentsRoot, { withFileTypes: true })
    .filter((entry) => !entry.isDirectory() && entry.name.endsWith('.md'))
    .map((entry) => `agents/${entry.name}`)
    .filter((relative) => !plan.has(relative))
    .toSorted();
};

export const syncConsolidatedPlugin = (repoRoot: string, check = false): string[] => {
  const packageRoot = path.resolve(repoRoot, 'packages/plugin');
  const plan = outputPlan(packageRoot);
  const stale = staleAgents(packageRoot, plan);
  const changed: string[] = [];
  for (const [relative, content] of plan) {
    const absolute = assertContainedFile(packageRoot, relative);
    if (!fs.existsSync(absolute) || fs.readFileSync(absolute, 'utf-8') !== content) {
      changed.push(relative);
    }
  }
  for (const relative of stale) {
    assertContainedFile(packageRoot, relative);
  }
  if (!check) {
    for (const relative of changed) {
      const absolute = path.join(packageRoot, relative);
      fs.mkdirSync(path.dirname(absolute), { recursive: true });
      fs.writeFileSync(absolute, plan.get(relative) ?? '', 'utf-8');
    }
    for (const relative of stale) {
      fs.unlinkSync(path.join(packageRoot, relative));
    }
  }
  return [...changed, ...stale].toSorted();
};

export const main = (
  args: string[],
  repoRoot = path.resolve(import.meta.dirname, '..'),
): number => {
  if (args.length > 1 || (args.length === 1 && !['--check', '--write'].includes(args[0]))) {
    console.error('Usage: sync-consolidated-plugin.ts [--check|--write]');
    return 2;
  }
  try {
    const check = args[0] === '--check';
    const changes = syncConsolidatedPlugin(repoRoot, check);
    for (const relative of changes) {
      console.log(`${check ? 'DRIFT' : 'SYNC'}: packages/plugin/${relative}`);
    }
    return check && changes.length > 0 ? 1 : 0;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 2;
  }
};

if (process.argv[1] && path.resolve(process.argv[1]) === import.meta.filename) {
  process.exitCode = main(process.argv.slice(2));
}
