#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'yaml';

const ROLES = ['adventurer', 'architect', 'builder', 'diagnose', 'planner', 'reviewer', 'writer'];
const MODES = ['blitz', 'fein', 'sonar'];
const SHARED_SKILLS = [
  ...ROLES,
  ...MODES,
  'orchestrator',
  'global-rules',
  'handoff',
  'iteration-limits',
];
const NOTICE =
  '<!-- Generated by scripts/sync-consolidated-plugin.ts. Edit its inputs and regenerate. -->';
const HOST_LIMIT =
  'Live host loading is unverified. Package and sync checks validate the shipped files, not runtime discovery or enforcement.';
const VERIFIED_HOST_LIMITS: Record<string, string> = {
  'claude-code':
    'Claude Code 2.1.217 native reviewer dispatch, shared skill preloading, and Write/Edit tool-schema exclusion passed an offline fixture probe. This does not evaluate model judgment, every specialist, shell-mediated editing, or other host versions. See the repository host-verification record for reproduction and limits.',
  hermes:
    'Portable plugin doctor and isolated packed-skill discovery were verified during consolidation. End-to-end task behavior, delegation, and runtime enforcement remain unverified.',
  omp: 'OMP 18.4.8 installed-loader and capability-provider discovery passed against a packed archive in a manually constructed npm-layout fixture. The npm installation transaction, live session/task execution, permissions, and enforcement remain unverified. See the repository host-verification record for reproduction and limits.',
};
const CORE_CONTEXTS = [
  ['claude-code', 'integrations/claude-code.md', '## Claude Code Integration'],
  ['cursor', 'integrations/cursor.md', '## Specialist Agents (Cursor)'],
  ['codex', 'integrations/codex.md', '## Codex CLI Integration'],
  ['kimi-code', 'integrations/kimi-code.md', '## Specialist → Subagent Routing'],
] as const;
const MANIFESTS = [
  ['generation/manifests/plugin.json', 'plugin.json'],
  ['generation/manifests/claude-code.json', '.claude-plugin/plugin.json'],
  ['generation/manifests/codex.json', '.codex-plugin/plugin.json'],
  ['generation/manifests/cursor.json', '.cursor-plugin/plugin.json'],
  ['generation/manifests/devin.json', '.devin-plugin/plugin.json'],
  ['generation/manifests/zcode.json', '.zcode-plugin/plugin.json'],
  ['generation/manifests/kimi.plugin.json', 'kimi.plugin.json'],
] as const;
const HOSTS = ['claude-code', 'codex', 'cursor', 'devin', 'hermes', 'kimi-code', 'omp', 'zcode'];
const RETIRED_OUTPUTS = [
  'agents/orchestrator.md',
  ...MODES.map((mode) => `commands/modes/${mode}.md`),
  'rules/global/global-rules.md',
  'skills/handoff.md',
  'skills/iteration-limits.md',
  ...HOSTS.map((host) => `integrations/${host}/context.md`),
  ...MODES.flatMap((mode) => [
    `integrations/cursor/commands/${mode}.md`,
    `integrations/kimi-code/commands/${mode}.md`,
  ]),
  'integrations/cursor/rules/maestria-global.mdc',
  'integrations/codex/instructions/AGENTS.md',
  ...MANIFESTS.map(([, output]) => `plugin/${output}`),
  'plugin/package.json',
  'plugin/README.md',
  'plugin/INSTALL.md',
  'plugin/LICENSE',
  'plugin/docs/support.md',
  'plugin/assets/cursor/logo.svg',
  ...ROLES.flatMap((role) => [
    `plugin/agents/${role}.md`,
    `plugin/agents/claude-code/${role}.md`,
    `plugin/agents/cursor/${role}.md`,
    `plugin/agents/codex/maestria-${role}.toml`,
  ]),
  ...SHARED_SKILLS.map((skill) => `plugin/skills/${skill}/SKILL.md`),
  ...HOSTS.map((host) => `plugin/integrations/${host}/README.md`),
  ...MODES.flatMap((mode) => [
    `plugin/integrations/cursor/commands/${mode}.md`,
    `plugin/integrations/kimi-code/commands/${mode}.md`,
  ]),
  'plugin/integrations/cursor/rules/maestria-global.mdc',
  'plugin/integrations/codex/instructions/AGENTS.md',
];

const assertContainedFile = (root: string, relative: string): string => {
  const absolute = path.resolve(root, relative);
  if (!absolute.startsWith(`${root}${path.sep}`)) {
    throw new Error(`Resource escapes package root: ${relative}`);
  }
  let current = path.parse(absolute).root;
  for (const part of absolute.slice(current.length).split(path.sep)) {
    current = path.join(current, part);
    let linked = false;
    try {
      linked = fs.lstatSync(current).isSymbolicLink();
    } catch (error) {
      if (!(error instanceof Error && 'code' in error && error.code === 'ENOENT')) {
        throw error;
      }
    }
    if (linked) {
      throw new Error(`Plugin resource must not be a symlink: ${relative}`);
    }
  }
  return absolute;
};

const readInput = (root: string, relative: string): string => {
  const absolute = assertContainedFile(root, relative);
  if (!fs.existsSync(absolute) || !fs.statSync(absolute).isFile()) {
    throw new Error(`Required plugin input is missing or not a file: ${relative}`);
  }
  return fs.readFileSync(absolute, 'utf-8');
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

const removeEmptyDirectories = (absolute: string): void => {
  if (!fs.existsSync(absolute) || !fs.statSync(absolute).isDirectory()) {
    return;
  }
  for (const entry of fs.readdirSync(absolute, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      removeEmptyDirectories(path.join(absolute, entry.name));
    }
  }
  if (fs.readdirSync(absolute).length === 0) {
    fs.rmdirSync(absolute);
  }
};

const validateRole = (text: string, role: string): void => {
  const match = /^---\n(?<frontmatter>[\s\S]*?)\n---\n(?<body>[\s\S]*)$/u.exec(text);
  if (!match?.groups) {
    throw new Error(`Missing agent frontmatter: ${role}`);
  }
  const metadata: unknown = parse(match.groups.frontmatter);
  if (!isRecord(metadata)) {
    throw new Error(`Invalid agent frontmatter: ${role}`);
  }
  const { name, description } = metadata;
  if (name !== role || typeof description !== 'string' || description.trim() === '') {
    throw new Error(`Invalid name or description in agent frontmatter: ${role}`);
  }
};

const hostLimit = (host: string): string => VERIFIED_HOST_LIMITS[host] ?? HOST_LIMIT;

const nativeGuide = (host: string, context: string): string => {
  const prefixes: Record<string, string> = { 'claude-code': 'maestria:', codex: 'maestria-' };
  const prefix = prefixes[host] ?? '';
  const agents = ROLES.map((role) => ({ agent: `\`${prefix}${role}\``, role }));
  const roleWidth = Math.max('Portable role'.length, ...agents.map(({ role }) => role.length));
  const agentWidth = Math.max('Native agent'.length, ...agents.map(({ agent }) => agent.length));
  const mapping =
    host === 'kimi-code'
      ? ''
      : `| ${'Portable role'.padEnd(roleWidth)} | ${'Native agent'.padEnd(agentWidth)} |\n| ${'-'.repeat(roleWidth)} | ${'-'.repeat(agentWidth)} |\n${agents
          .map(({ agent, role }) => `| ${role.padEnd(roleWidth)} | ${agent.padEnd(agentWidth)} |`)
          .join('\n')}\n\n`;
  return `${NOTICE}\n\n# ${host} Integration\n\nRead this guide only when ${host} is the active host. The shared portable skills define methodology; the host owns tools, delegation, permissions, and lifecycle.\n\n${mapping}${context.trim()}\n\n${hostLimit(host)}\n`;
};

const advisoryGuide = (host: 'devin' | 'zcode'): string => {
  const hostText =
    host === 'devin'
      ? 'Devin loads the shared skills from `skills/` and the conventional root `agents/<role>.md` profiles as `maestria:<role>`. Custom plugin subagents are available in local CLI and Desktop sessions, not cloud sessions. Use the host-provided subagent controls with a complete handoff; this package does not prescribe a fabricated tool API. Workflow modes are skills: `/maestria:fein`, `/maestria:sonar`, and `/maestria:blitz`.\n\nSee the [Devin plugin file format](https://docs.devin.ai/cli/extensibility/plugins/overview) and the [Customize product guide](https://docs.devin.ai/product-guides/plugins).'
      : 'ZCode selects the shared `skills/` corpus and the explicit root `agents/<role>.md` files through `.zcode-plugin/plugin.json`. Use the installed plugin subagents through the controls the host exposes. The manifest disables command discovery; invoke the fein, sonar, and blitz skills through the Skills group. It does not load the Claude or Cursor command prompts or assume their delegation API.\n\nSee the [ZCode plugin documentation](https://zcode.z.ai/en/docs/plugin).';
  return `${NOTICE}\n\n# ${host} Integration\n\n${hostText}\n\nLoad global-rules once per session. Keep exploration, planning, and review read-only and retain independent maker/checker roles. The root agent profiles contain name and description frontmatter plus portable role guidance. Their restrictions are advisory; no runtime tool-denial or sandbox setting is claimed for these hosts.\n\n${HOST_LIMIT}\n`;
};

const hermesGuide = (): string => `${NOTICE}

# Hermes Integration

Hermes consumes the root Agent Plugins v1 manifest and shared skills. Enable the staged package explicitly through the host's plugin flow, then use \`skills_list\` to discover each full qualified name and \`skill_view\` to load it. Hermes generates an \`agent-plugin-<slug>-<hash>\` namespace; do not assume \`maestria:<skill>\`.

Load global-rules and orchestrator by their discovered names. Apply portable role guidance within the tools and delegation controls the host exposes. Portable skills do not supply a trust policy, permissions, or sandbox. This bundle includes no Python adapter, native Hermes hooks, or MCP declaration.

See [Hermes portable package support](https://hermes-agent.nousresearch.com/docs/developer-guide/plugins#portable-agent-plugins-v1-packages).

${hostLimit('hermes')}
`;

const ompGuide = (): string => `${NOTICE}

# OMP Integration

OMP (Oh My Pi) uses \`package.json#omp\` for npm registration and the root Agent Plugins manifest for shared skill discovery. The empty \`omp\` object registers the package without an executable extension. Root \`agents/*.md\` are advisory profiles; host-specific commands and rules live under explicit host subdirectories and are not conventional OMP resources. Install the staged package through the host plugin flow (\`maestria install omp\` stages \`@maestria/agent-plugins\` via \`omp plugin install\`), then load the \`global-rules\` and \`orchestrator\` skills in session. If the retired \`@maestria/omp\` native package is still installed, remove it first (\`omp plugin uninstall @maestria/omp\`) so its executable hooks do not shadow the portable skills.

## Specialist → task() Routing

Dispatch each persona through OMP's native \`task(agent, task)\` tool. The root advisory profiles carry embedded role methodology because their consumers do not share a guaranteed skill-preload contract. Dispatch through the native tools actually available in the session, and carry the global-rules contract and task constraints into each child. Skill loading in the parent does not automatically populate child context.

| Persona | Native dispatch | When |
| --- | --- | --- |
| adventurer | \`task(agent: "adventurer", task: "...")\` | Before implementation in unfamiliar code |
| architect | \`task(agent: "architect", task: "...")\` | When multiple approaches exist |
| builder | \`task(agent: "builder", task: "...")\` | When the design is locked |
| diagnose | \`task(agent: "diagnose", task: "...")\` | When something is broken |
| planner | \`task(agent: "planner", task: "...")\` | Before multi-step work |
| reviewer | \`task(agent: "reviewer", task: "...")\` | After the integrated builder batch is reconciled |
| writer | \`task(agent: "writer", task: "...")\` | When code needs human-facing docs |

## Session-Start Behavior

No maestria code runs at session start. The retired native package deployed agent files to \`~/.omp/agent/agents/\`, injected mode prompts on \`before_agent_start\`, preserved session state across compaction, mirrored OMP goal state, and intercepted tool calls; none of that ships here. Load \`global-rules\` once per session and the \`orchestrator\` skill to route work; keep exploration, planning, and review read-only and retain independent maker/checker roles. Invoke the fein, sonar, and blitz workflow modes as skills, not slash commands: the retired \`/fein\`, \`/sonar\`, \`/blitz\`, \`/review\`, \`/restore-model\`, \`/review-model\`, \`/handoff\`, and \`/maestria-status\` commands are gone, and per-agent model frontmatter (\`maestria configure omp\`) no longer applies.

The shared portable skills define methodology; the host owns tools, delegation, permissions, and lifecycle. This bundle includes no executable extension, no \`maestria_subagent\` wrapper tool, no review-mode enforcement, and no MCP declaration.

See [Oh My Pi](https://omp.sh/).

${hostLimit('omp')}
`;

const addOutput = (plan: Map<string, string>, relative: string, content: string): void => {
  if (plan.has(relative)) {
    throw new Error(`Duplicate plugin output path: ${relative}`);
  }
  plan.set(relative, content);
};

export const preflightPluginPaths = (repoRoot: string): void => {
  const packageRoot = path.resolve(repoRoot, 'packages/agent-plugins');
  const resources = [
    ...RETIRED_OUTPUTS,
    ...MANIFESTS.flatMap(([source, output]) => [source, output]),
    ...ROLES.flatMap((role) => [
      `agents/${role}.md`,
      `agents/claude-code/${role}.md`,
      `agents/cursor/${role}.md`,
      `agents/codex/maestria-${role}.toml`,
      `generation/codex/maestria-${role}.toml`,
    ]),
    ...SHARED_SKILLS.map((skill) => `skills/${skill}/SKILL.md`),
    ...HOSTS.map((host) => `integrations/${host}/README.md`),
    ...MODES.flatMap((mode) => [`commands/cursor/${mode}.md`, `commands/kimi-code/${mode}.md`]),
    'rules/cursor/maestria-global.mdc',
    'rules/codex/instructions/AGENTS.md',
  ];
  for (const relative of resources) {
    const absolute = assertContainedFile(packageRoot, relative);
    if (fs.existsSync(absolute) && !fs.statSync(absolute).isFile()) {
      throw new Error(`Plugin resource is not a file: ${relative}`);
    }
  }
};

const validateRuntimeResources = (packageRoot: string): void => {
  for (const role of ROLES) {
    validateRole(readInput(packageRoot, `agents/${role}.md`), role);
    for (const host of ['claude-code', 'cursor']) {
      readInput(packageRoot, `agents/${host}/${role}.md`);
    }
  }
  for (const skill of SHARED_SKILLS) {
    readInput(packageRoot, `skills/${skill}/SKILL.md`);
  }
  for (const mode of MODES) {
    readInput(packageRoot, `commands/cursor/${mode}.md`);
    readInput(packageRoot, `commands/kimi-code/${mode}.md`);
  }
  readInput(packageRoot, 'rules/cursor/maestria-global.mdc');
  readInput(packageRoot, 'rules/codex/instructions/AGENTS.md');
};

const addPackageMetadata = (plan: Map<string, string>, packageRoot: string): void => {
  for (const [source, output] of MANIFESTS) {
    addOutput(plan, output, readInput(packageRoot, source));
  }
};

const addNativeProfiles = (plan: Map<string, string>, packageRoot: string): void => {
  for (const role of ROLES) {
    addOutput(
      plan,
      `agents/codex/maestria-${role}.toml`,
      readInput(packageRoot, `generation/codex/maestria-${role}.toml`),
    );
  }
};

const addIntegrationGuides = (plan: Map<string, string>, repoRoot: string): void => {
  const coreRoot = path.resolve(repoRoot, 'packages/core/agent-directives');
  for (const [host, source, heading] of CORE_CONTEXTS) {
    const text = readInput(coreRoot, source);
    const start = text.indexOf(heading);
    if (start === -1) {
      throw new Error(`Missing native integration heading ${heading}: ${source}`);
    }
    addOutput(plan, `integrations/${host}/README.md`, nativeGuide(host, text.slice(start)));
  }
  for (const host of ['devin', 'zcode'] as const) {
    addOutput(plan, `integrations/${host}/README.md`, advisoryGuide(host));
  }
  addOutput(plan, 'integrations/hermes/README.md', hermesGuide());
  addOutput(plan, 'integrations/omp/README.md', ompGuide());
};

const outputPlan = (repoRoot: string, packageRoot: string): Map<string, string> => {
  const plan = new Map<string, string>();
  validateRuntimeResources(packageRoot);
  addPackageMetadata(plan, packageRoot);
  addNativeProfiles(plan, packageRoot);
  addIntegrationGuides(plan, repoRoot);
  return plan;
};

const pruneEmptyDirectories = (root: string, relative: string): void => {
  const absolute = assertContainedFile(root, relative);
  removeEmptyDirectories(absolute);
};

export const syncConsolidatedPlugin = (repoRoot: string, check = false): string[] => {
  preflightPluginPaths(repoRoot);
  const packageRoot = path.resolve(repoRoot, 'packages/agent-plugins');
  const plan = outputPlan(repoRoot, packageRoot);
  const stale = RETIRED_OUTPUTS.filter((relative) => {
    const absolute = assertContainedFile(packageRoot, relative);
    return fs.existsSync(absolute);
  });
  const changed: string[] = [];

  for (const [relative, content] of plan) {
    const absolute = assertContainedFile(packageRoot, relative);
    if (!fs.existsSync(absolute) || fs.readFileSync(absolute, 'utf-8') !== content) {
      changed.push(relative);
    }
  }
  for (const relative of stale) {
    const absolute = assertContainedFile(packageRoot, relative);
    if (!fs.statSync(absolute).isFile()) {
      throw new Error(`Retired output is not a file: ${relative}`);
    }
  }

  if (!check) {
    for (const relative of changed) {
      const absolute = path.join(packageRoot, relative);
      fs.mkdirSync(path.dirname(absolute), { recursive: true });
      fs.writeFileSync(absolute, plan.get(relative) ?? '', 'utf-8');
    }
    for (const relative of stale) {
      fs.unlinkSync(path.join(packageRoot, relative));
    }
    pruneEmptyDirectories(packageRoot, 'plugin');
    pruneEmptyDirectories(packageRoot, 'commands/modes');
    pruneEmptyDirectories(packageRoot, 'rules/global');
    pruneEmptyDirectories(packageRoot, 'integrations');
  }
  return [...changed, ...stale].toSorted();
};

export const main = (
  args: string[],
  repoRoot = path.resolve(import.meta.dirname, '..'),
): number => {
  if (
    args.length > 1 ||
    (args.length === 1 && !['--check', '--write', '--preflight'].includes(args[0]))
  ) {
    console.error('Usage: sync-consolidated-plugin.ts [--check|--write|--preflight]');
    return 2;
  }
  try {
    if (args[0] === '--preflight') {
      preflightPluginPaths(repoRoot);
      return 0;
    }
    const check = args[0] === '--check';
    const changes = syncConsolidatedPlugin(repoRoot, check);
    for (const relative of changes) {
      console.log(`${check ? 'DRIFT' : 'SYNC'}: packages/agent-plugins/${relative}`);
    }
    return check && changes.length > 0 ? 1 : 0;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 2;
  }
};

if (process.argv[1] && path.resolve(process.argv[1]) === import.meta.filename) {
  process.exitCode = main(process.argv.slice(2));
}
